Patch 1
YunoHost-Apps/mastodon_ynh pull request #311
Opened 2022-02-19 18:54 UTC by rosbeef

## Problem

- *No problem but improvement : Add ability to host user with different domain from server domain*

## Solution

- *Add well known host-meta file*
- *Add option to select users domain*

## PR Status

- [* ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

!testme

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

2022-02-19 20:23 UTC, Tagadda requested changes
Wow :open_mouth: This looks nice!
I suggested minor changes~

2022-02-19 20:23 UTC, Tagadda commented on scripts/install
> +if yunohost --output-as plain domain list | grep -q "^$userdomain$"
I'm not sure why we check that... $userdomain should already be a valid domain, it's a `domain` in the manifest.
But we should check if we really need the redirection. If `domain` and `userdomain` are the same domain, we shouldn't add the file.
```suggestion
if [[ ! "$userdomain" == "$domain" ]]
```

2022-02-19 20:23 UTC, Tagadda commented on scripts/install
> +
```suggestion
```
This doesn't do anything?

2022-02-19 20:23 UTC, Tagadda commented on scripts/install
> +#fi
```suggestion
if [[ ! "$userdomain" == "$domain" ]]; then
    ynh_permission_create --permission=server_client_infos --url=$userdomain/.well-known/host-meta \
                          --label="Server info for clients. (well-known)" --show_tile=false --allowed=visitors \
                          --auth_header=false --protected=true
fi
```
Something like that should work. But if `is_public` is false, the permission should not be protected, and should not allow visitors.
Maybe move this down in the `SETUP SSOWAT` section?

2022-02-19 20:41 UTC, rosbeef commented on scripts/install
> +
seems not ;) sorry it's my first PR and not so good in dev ;)

2022-02-19 20:43 UTC, rosbeef commented on scripts/install
> +#fi
I used synapse package as example but i don know if it applies to mastodon.
i'm not so good with github. maybe it shoud not be in this PR

2022-02-19 20:45 UTC, rosbeef commented
maybe it should be improved before publish.
i based my mod no https://docs.joinmastodon.org/dev/routes/

2022-02-20 00:30 UTC, rosbeef commented
as it tell on https://dallas.lu/en/use-your-primary-domain-as-an-mastodon-name
fediverse servers like peertube which do not look for host-meta, should not work with main domain to subscribe to the video.
but subdomain should work

2022-02-20 01:33 UTC, rosbeef commented
i don't find to make peertube subscription working with something like this in __HOSTDOMAIN__ :
location ~* ./well-known/webfinger {
    add_header Access-Control-Allow-Origin __USERDOMAIN__;
}

it should allow __HOSTDOMAIN__ to recieve crossSite request from __USERDOMAIN

2022-02-27 19:08 UTC, Tagadda requested changes
All those redirections don't make much sense. We only need `/.well-known/host-meta` and `/.well-known/webfinger` on the `LOCAL_DOMAIN`.

I think you miss the `https` in front on the domain in `Access-Control-Allow-Origin`.

2022-02-27 19:08 UTC, Tagadda commented on conf/maindomain_nginx.conf
> +}
```suggestion
location ~ ^/.well-known/(webfinger|host-meta) {
 return 301 https://__DOMAIN__$request_uri;
}
```

2022-02-27 19:08 UTC, Tagadda commented on conf/maindomain_nginx.conf
> +}
```suggestion
```

2022-02-27 22:20 UTC, yalh76 commented
!testme

2022-02-28 16:33 UTC, rosbeef commented
i don't understand how to mitigate the Cross-Origin error ,
i put 
```
location ~* /.well-known/webfinger {
    add_header Access-Control-Allow-Origin https://__USERDOMAIN__;
}
```
in /etc/nginx/conf.d/__DOMAIN__.d/mastodon.conf
but peertube always return me a cors error

2022-02-28 16:59 UTC, Tagadda commented
Maybe `Access-Control-Allow-Origin https://__USERDOMAIN__ https://__DOMAIN__;` ?

2022-03-03 00:12 UTC, rosbeef commented
Appart script errors: i added parcial CORS mitigation
add:header Access-Control-Allow-Origin * to USERDOMAIN nginx conf

2022-03-03 01:10 UTC, yalh76 commented
!testme

2022-03-03 01:10 UTC, yalh76 commented
!testme

2022-03-04 00:07 UTC, rosbeef commented
!testme

2022-03-05 18:31 UTC, rosbeef commented
except for a bug that that i don't understand (mastodon can not find own served peertube on subscription from peertube with a mastodon account)
all is working for me.
And testing restore and upgrade most of time fail due to lake of space. @yalh76  have you an idea how to solve this problem ?

2022-03-06 14:51 UTC, yalh76 commented
!testme

2022-03-25 23:51 UTC, rosbeef commented
!testme

2022-03-31 22:53 UTC, rosbeef commented
@yalh76 !testme ;)

2022-11-05 15:53 UTC, ericgaspar commented
!testme

2022-12-21 19:18 UTC, rosbeef commented
i would take back my work on this pr but mixed up with push and saw that i was working on master...
are some one could help me to clean my pr and start back my workis it possible to revert my last forced-push action ?

formy information ; (To install Mastodon on mastodon.example.com in such a way it can serve @alice@example.com, set LOCAL_DOMAIN to example.com and WEB_DOMAIN to mastodon.example.com. This also requires additional configuration on the server hosting example.com to redirect or proxy requests to https://example.com/.well-known/webfinger to https://mastodon.example.com/.well-known/webfinger. For instance, with nginx, the configuration could look like the following:

location /.well-known/webfinger {
  add_header Access-Control-Allow-Origin '*';
  return 301 https://mastodon.example.com$request_uri;
}
) https://docs.joinmastodon.org/admin/config/#local_domain

2023-01-24 09:11 UTC, merged

2023-01-24 13:19 UTC, rosbeef commented
Hi @ericgaspar you merged but it does noting. Some days ago I' be made a sync from source and all my modification were lost. I don't know how to go back.
Maybe it should be better to make an other PR but I would recover my last job to take it as example as i did it a long time ago.